name: Deployment

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set ssh key
        run: |
          mkdir $HOME/.ssh
          echo "${{ secrets.DEV_SSH_KEY }}" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"
      - name: Deploy via rsync
        run: |
          rsync -a --stats --delete --exclude-from .github/rsync-exclude-dev \
          -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" \
          ./ ${{ secrets.DEV_USERNAME }}@${{ secrets.DEV_IP }}:${{ secrets.DEV_DESTINATION }}
      - name: Build on server
        run: |
          ssh -i $HOME/.ssh/key ${{ secrets.DEV_USERNAME }}@${{ secrets.DEV_IP }} \
          "cd ${{ secrets.DEV_DESTINATION }} && npm i && npm run build"
